{% set name = "reciprocalspaceship" %}
{% set version = "1.0.8" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/reciprocalspaceship-{{ version }}.tar.gz
  sha256: d2cb863930a337677e62904009bc3adaf7a625b0539be9edf400a9d8e2a57f73

build:
  number: 0
  noarch: python
  entry_points:
    - rs.mtzdump=reciprocalspaceship.commandline.mtzdump:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - gemmi >=0.7.0,<=0.7.3
    - ipython
    - numpy
    - pandas >=2.2.2,<=2.3.3
    - python >={{ python_min }}
    - scipy
    - msgpack-python
    - setuptools
    - joblib

test:
  imports:
    - reciprocalspaceship
    - reciprocalspaceship.algorithms
  commands:
    - pip check
    - rs.mtzdump --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/reciprocalspaceship/
  doc_url: https://rs-station.github.io/reciprocalspaceship/
  dev_url: https://github.com/rs-station/reciprocalspaceship/
  summary: Tools for exploring reciprocal space
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JBGreisman
    - anthchirp
