{% set name = "reciprocalspaceship" %}
{% set version = "1.0.6" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reciprocalspaceship-{{ version }}.tar.gz
  sha256: f9a36a25cd50b46639a411d460aa7982c89a7c7e0dd20b5648cd5dcfee94e512

build:
  number: 0
  noarch: python
  entry_points:
    - rs.mtzdump=reciprocalspaceship.commandline.mtzdump:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - gemmi >=0.7.0,<=0.7.1
    - ipython
    - numpy
    - pandas >=2.2.2,<=2.2.3
    - python >={{ python_min }}
    - scipy
    - msgpack-python
    - setuptools

test:
  imports:
    - reciprocalspaceship
    - reciprocalspaceship.algorithms
  commands:
    - pip check
    - rs.mtzdump --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/reciprocalspaceship/
  doc_url: https://rs-station.github.io/reciprocalspaceship/
  dev_url: https://github.com/rs-station/reciprocalspaceship/
  summary: Tools for exploring reciprocal space
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JBGreisman
    - anthchirp
