{% set name = "reciprocalspaceship" %}
{% set version = "0.9.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reciprocalspaceship-{{ version }}.tar.gz
  sha256: bbe3761988090ace371680c1d6389a9182e2729578d94b2962b233f7cb882c2c

build:
  number: 0
  noarch: python
  entry_points:
    - rs.mtzdump=reciprocalspaceship.commandline.mtzdump:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - gemmi >=0.4.2
    - ipython
    - numpy
    - pandas >=1.2.0,<=1.3.0
    - python >=3.7
    - scipy

test:
  imports:
    - reciprocalspaceship
    - reciprocalspaceship.algorithms
  commands:
    - pip check
    - rs.mtzdump --help
  requires:
    - pip

about:
  home: https://pypi.org/project/reciprocalspaceship/
  doc_url: https://hekstra-lab.github.io/reciprocalspaceship/
  dev_url: https://github.com/Hekstra-Lab/reciprocalspaceship/
  summary: Tools for exploring reciprocal space
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anthchirp
