{% set name = "reciprocalspaceship" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reciprocalspaceship-{{ version }}.tar.gz
  sha256: 880e3ff1ea3137f3895d3e9c3c427d737c203dc47fc93671dcf187db4e970dbd

build:
  number: 0
  noarch: python
  entry_points:
    - rs.mtzdump=reciprocalspaceship.commandline.mtzdump:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >3.7
  run:
    - gemmi >=0.5.5,<=0.5.7
    - ipython
    - numpy
    - pandas >=1.2.0,<=1.4.4
    - python >3.7
    - scipy

test:
  imports:
    - reciprocalspaceship
    - reciprocalspaceship.algorithms
  commands:
    - pip check
    - rs.mtzdump --help
  requires:
    - pip

about:
  home: https://pypi.org/project/reciprocalspaceship/
  doc_url: https://rs-station.github.io/reciprocalspaceship/
  dev_url: https://github.com/rs-station/reciprocalspaceship/
  summary: Tools for exploring reciprocal space
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JBGreisman
    - anthchirp
