{% set name = "reciprocalspaceship" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reciprocalspaceship-{{ version }}.tar.gz
  sha256: 4b39fab3b76f8ab219cb4ec0794da79dfe50d74dfa54eaa3d28c3017b9e9fb9d

build:
  number: 0
  noarch: python
  entry_points:
    - rs.mtzdump=reciprocalspaceship.commandline.mtzdump:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >3.7
  run:
    - gemmi >=0.5.5,<=0.5.5
    - ipython
    - numpy
    - pandas >=1.2.0,<=1.4.3
    - python >3.7
    - scipy

test:
  imports:
    - reciprocalspaceship
    - reciprocalspaceship.algorithms
  commands:
    - pip check
    - rs.mtzdump --help
  requires:
    - pip

about:
  home: https://pypi.org/project/reciprocalspaceship/
  doc_url: https://hekstra-lab.github.io/reciprocalspaceship/
  dev_url: https://github.com/Hekstra-Lab/reciprocalspaceship/
  summary: Tools for exploring reciprocal space
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JBGreisman
    - anthchirp
